// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorishitaAssignments.Models;

#nullable disable

namespace MorishitaAssignments.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230706021509_version1.3")]
    partial class version13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MorishitaAssignments.Models.Assignments", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"), 1L, 1);

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.ToTable("Assigns");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            AccessLevel = 1,
                            AssignmentName = "Assignment 6.1",
                            Link = ""
                        },
                        new
                        {
                            AssignmentId = 2,
                            AccessLevel = 5,
                            AssignmentName = "Assignment 7.1",
                            Link = ""
                        },
                        new
                        {
                            AssignmentId = 3,
                            AccessLevel = 9,
                            AssignmentName = "Assignment 8.5",
                            Link = ""
                        });
                });

            modelBuilder.Entity("MorishitaAssignments.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentAccessLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sharean",
                            Grade = "12",
                            LastName = "Vesey",
                            StudentAccessLevel = 9
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dewayne",
                            Grade = "9",
                            LastName = "Mori",
                            StudentAccessLevel = 6
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Esiah",
                            Grade = "9",
                            LastName = "Lonnell",
                            StudentAccessLevel = 6
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Elizabeth",
                            Grade = "8",
                            LastName = "Shalonda",
                            StudentAccessLevel = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
